# Generated by Django 6.0.2 on 2026-02-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_enrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
