# Generated by Django 6.0.2 on 2026-02-17 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_course_price_product_last_updated_alter_product_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='last_updated',
            new_name='updated_at',
        ),
        migrations.AddField(
            model_name='course',
            name='max_students',
            field=models.PositiveIntegerField(default=20),
        ),
    ]
