# Generated by Django 6.0.2 on 2026-02-18 14:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='course',
            name='max_students',
        ),
        migrations.AddField(
            model_name='course',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 18, 14, 26, 30, 407305, tzinfo=datetime.timezone.utc), help_text='When is the class?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='Course description coming soon'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.URLField(default='https://images.unsplash.com/photo-1556910103-1c02745a30bf'),
        ),
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='seats_available',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
